### ISSUE TITLE
Apprarent bug in InitErgmTerms.mindegree

### ISSUE THREAD

**Issue by sgoodreau** [statnet/ergm.userterms#1]
It would seem to me the lines 

```
u <- sort(unique(nodecov))
nodecov <- match(nodecov,u)
```
logically ought to be outside the if-else statement.  And indeed they are in the JSS paper.  

Can someone be a second set of eyes on this to confirm my logic?

**Comment by chad-klumb** [comment]
Appears fine to me.

If a$by is NULL, then there is no nodecov to use, and the changestat function never looks beyond the first two entries (attrflag and mindeg) in the input params vector anyway.

If you execute 

``` CODE
u <- sort(unique(nodecov))
nodecov <- match(nodecov, u)
```

with nodecov initially set to NULL (as it is when a$by is NULL) then you get integer(0) back for nodecov at the end.  If you concatenate integer(0), as in the line

```CODE
inputs = c(attrflag, a$mindeg, nodecov)
```

with nodecov = integer(0), it doesn't change the vector.  Nor does concatenating with nodecov = NULL instead.

So, I think pulling those two lines you quoted out of the if-else would produce equivalent output, but their behavior is trivial unless a$by is non-NULL.

**Comment by krivit** [comment]
We probably want to port this to the nodal attributes UI.

**Comment by chad-klumb** [comment]
Yes, that's what got me looking here in the first place.

**Comment by sgoodreau** [comment]
Makes sense, @chad-klumb , thanks.  I'm closing.
